---
title: "Final Report"
format: pdf
---
```{r, echo = FALSE, message=FALSE}
library(readr)
library(janitor)
library(dplyr)
library(performance)
library(patchwork)
library(see)
library(ggplot2)
library(here)
library(car)
library(GGally)
library(modelsummary)
library(tidyverse)
library(emmeans)
library(modelsummary)
```

```{r, echo = FALSE, message=FALSE}
Life_Expectancy <- read_csv(here("Life_Expectancy_00_15.csv"))
Life<-clean_names(Life_Expectancy)
Life<-Life|>filter(year==2015)
```

```{r, echo = FALSE, message=FALSE}
Life|>
  select(-continent,-least_developed,-country,-year) |> 
  ggpairs()
```

```{r, echo = FALSE, message=FALSE}
Life|>
  select(people_using_at_least_basic_drinking_water_services, individuals_using_the_internet, gdp_per_capita, obesity_among_adults, people_practicing_open_defecation, electric_power_consumption, health_expenditure) |> 
  ggpairs()
```

$$
\begin{aligned}
{\text{The model named "additive" contains only three numeric variables:}}\\
\widehat {\text{life_expectancy}} = \hat{\beta}_{0} + \hat{\beta}_{1}\cdot {\text{gdp_per_capita}}\ + \hat{\beta}_{2}\cdot{\text{health_expenditure}}\\
+\hat{\beta}_{3} \cdot{\text{people_using_at_least_basic_drinking_water_services}}\\
\end{aligned}
$$

```{r, echo = FALSE, message=FALSE}
additive<-lm(data = Life, life_expectancy ~ gdp_per_capita + health_expenditure + people_using_at_least_basic_drinking_water_services )
summary(additive)
```


$$
\begin{aligned}
\widehat {\text{life_expectancy}} = \hat{\beta}_{0} + \hat{\beta}_{1}\cdot {\text{gdp_per_capita}}\ + \hat{\beta}_{2}\cdot{\text{health_expenditure}}\\
+\hat{\beta}_{3} \cdot{\text{people_using_at_least_basic_drinking_water_services}}\\
+ \hat{\beta}_{4} \cdot \mathbb{1}_{\text{Asia}}({\text{continent}}) + \hat{\beta}_{5} \cdot \mathbb{1}_{\text{Europe}}({\text{continent}}) \\
+ \hat{\beta}_{6} \cdot \mathbb{1}_{\text{North America}}({\text{continent}}) 
+ \hat{\beta}_{7} \cdot \mathbb{1}_{\text{Oceania}}({\text{continent}})\\
+ \hat{\beta}_{8} \cdot \mathbb{1}_{\text{South America}}({\text{continent}})
\end{aligned}
$$

```{r, echo = FALSE, message=FALSE}
additive_w_continent<-lm(data = Life, life_expectancy ~ gdp_per_capita + health_expenditure + people_using_at_least_basic_drinking_water_services+continent)
summary(additive_w_continent)
check_model(additive_w_continent, check = c("ncv","homogeneity","qq"))
vif(additive_w_continent)
anova(additive, additive_w_continent)
```


$$
\begin{aligned}
\widehat {\text{life_expectancy}} = \hat{\beta}_{0} + \hat{\beta}_{1}\cdot {\text{gdp_per_capita}}\ + \hat{\beta}_{2}\cdot{\text{health_expenditure}}\\
+\hat{\beta}_{3} \cdot{\text{people_using_at_least_basic_drinking_water_services}}\\
+ \hat{\beta}_{4} \cdot \mathbb{1}_{\text{TRUE}}({\text{least_developed}})
\end{aligned}
$$
```{r, echo = FALSE, message=FALSE}
additive_w_least_developed<-lm(data = Life, life_expectancy ~ gdp_per_capita + health_expenditure + people_using_at_least_basic_drinking_water_services+least_developed)
summary(additive_w_least_developed)
check_model(additive_w_least_developed, check = c("ncv","homogeneity","qq"))
vif(additive_w_least_developed)
anova(additive, additive_w_least_developed)
```
Model Summary
```{r, echo = FALSE, message=FALSE}
models <- list("additive" = additive,
               "additive_w_least_developed" = additive_w_least_developed,
               "additive_w_continent" = additive_w_continent)
options(modelsummary_format_numeric_latex = "plain")
    modelsummary(models,
                 estimate="{estimate}{stars}",
                 notes = list('+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001')
                 )
```

```{r, echo = FALSE, message=FALSE}
mean_drinking=mean(Life$people_using_at_least_basic_drinking_water_services)
mean_health_expenditure=mean(Life$health_expenditure)
mean_gdp=mean(Life$gdp_per_capita)
Life |> 
  summarise(mean_drinking = mean(people_using_at_least_basic_drinking_water_services),
            mean_health_expenditure = mean(health_expenditure),
            mean_gdp = mean(gdp_per_capita))
```

```{r, echo = FALSE, message=FALSE}
##This contrast fix all three at once
continent_grid <- emmeans(additive_w_continent, specs = ~continent,
                 at = list(drinking = mean_drinking, 
                           health = mean_health_expenditure,
                           gdp = mean_gdp
                           )
                )
contrast(continent_grid, method = "pairwise")
```

```{r, echo = FALSE, message=FALSE}
least_developed_grid <- emmeans(additive_w_least_developed, specs = ~least_developed,
                 at = list(drinking = mean_drinking, 
                           health = mean_health_expenditure,
                           gdp = mean_gdp
                           )
                )
contrast(least_developed_grid, method = "pairwise")
```