---
title: "Project code"
format: html
---

```{r}
library(readr)
library(janitor)
library(dplyr)
library(performance)
library(patchwork)
library(see)
library(ggplot2)
library(here)
library(car)
library(GGally)
library(modelsummary)
```

```{r}
Life_Expectancy <- read_csv(here("Life_Expectancy_00_15.csv"))
Life<-clean_names(Life_Expectancy)
Life<-Life|>filter(year==2015)
```
Process to derive final regression-bivariate regression
```{r}
gdp_reg<-lm(data=Life,life_expectancy~gdp_per_capita)
summary(gdp_reg)

health_reg<-lm(data=Life,life_expectancy~health_expenditure)
summary(health_reg)

co2_reg <- lm(data = Life, life_expectancy ~ co2_emissions)
summary(co2_reg)

water_reg <- lm(data=Life, life_expectancy ~ people_using_at_least_basic_drinking_water_services)
summary(water_reg)

defacation_reg <- lm(data = Life, life_expectancy ~ people_practicing_open_defecation)
summary(defacation_reg)

```
Process to derive final regression-additive and interaction regression
```{r}
additive<-lm(data = Life, life_expectancy ~ gdp_per_capita + health_expenditure + co2_emissions + people_using_at_least_basic_drinking_water_services + people_practicing_open_defecation )
summary(additive)

additive2<-lm(data = Life, life_expectancy ~ gdp_per_capita + health_expenditure + co2_emissions + people_using_at_least_basic_drinking_water_services )
summary(additive2)

additive3<-lm(data = Life, life_expectancy ~ gdp_per_capita + health_expenditure + people_using_at_least_basic_drinking_water_services )
summary(additive3)
```

```{r}
additive_w_continent<-lm(data = Life, life_expectancy ~ gdp_per_capita + health_expenditure + people_using_at_least_basic_drinking_water_services+continent)
summary(additive_w_continent)

additive_w_least_developed<-lm(data = Life, life_expectancy ~ gdp_per_capita + health_expenditure + people_using_at_least_basic_drinking_water_services+least_developed)
```

```{r}
#just numeric variable
additive5<-lm(data = Life, life_expectancy ~ gdp_per_capita + health_expenditure + people_using_at_least_basic_drinking_water_services)
summary(additive5)
check_model(additive5, check = c("ncv","homogeneity","qq"))
```

```{r}
interaction1<-lm(data = Life, life_expectancy ~ gdp_per_capita + health_expenditure + people_using_at_least_basic_drinking_water_services *least_developed)
summary(interaction1)
anova(interaction1,additive_w_least_developed)
check_model(interaction1, check = c("ncv","homogeneity","qq"))
vif(interaction1) 
#high vif
interaction2<-lm(data = Life, life_expectancy ~ gdp_per_capita * least_developed+ health_expenditure + people_using_at_least_basic_drinking_water_services)
summary(interaction2)
vif(interaction2)
anova(interaction2,additive_w_least_developed)
check_model(interaction2, check = c("ncv","homogeneity","qq"))
#high vif and insignificant interaction term
#both interaction is not good 

```

```{r}
library(tidyverse)
library(emmeans)
```
Final Regression and contrast
```{r}
mean_drinking=mean(Life$people_using_at_least_basic_drinking_water_services)
mean_health_expenditure=mean(Life$health_expenditure)
mean_gdp=mean(Life$gdp_per_capita)
# Life<-Life|>mutate(gdp_c=gdp_per_capita-mean(Life$gdp_per_capita),
#              health_c=health_expenditure-mean(Life$health_expenditure),
#              drinking_c=people_using_at_least_basic_drinking_water_services-mean(Life$people_using_at_least_basic_drinking_water_services))


additive_w_continent<-lm(data = Life, life_expectancy ~ gdp_per_capita + health_expenditure + people_using_at_least_basic_drinking_water_services+continent)
summary(additive_w_continent)
check_model(additive_w_continent, check = c("ncv","homogeneity","qq"))
vif(additive_w_continent)
```

```{r}
##This contrast fix all three at once
continent_grid <- emmeans(additive_w_continent, specs = ~continent,
                 at = list(drinking = mean_drinking, 
                           health = mean_health_expenditure,
                           gdp = mean_gdp
                           )
                )
contrast(continent_grid, method = "pairwise")
```

```{r}
additive_w_least_developed<-lm(data = Life, life_expectancy ~ gdp_per_capita + health_expenditure + people_using_at_least_basic_drinking_water_services+least_developed)
summary(additive_w_least_developed)
check_model(additive_w_least_developed, check = c("ncv","homogeneity","qq"))
vif(additive_w_least_developed)
```

```{r}
least_developed_grid <- emmeans(additive_w_least_developed, specs = ~least_developed,
                 at = list(drinking = mean_drinking, 
                           health = mean_health_expenditure,
                           gdp = mean_gdp
                           )
                )
contrast(least_developed_grid, method = "pairwise")
```

```{r}
# developed_health<-lm(data=Life,life_expectancy~least_developed + health_expenditure)
# summary(developed_health)
# #africa is the baseline group
# 
# developed_gdp<-lm(data=Life,life_expectancy~least_developed + gdp_per_capita)
# summary(developed_gdp)
# 
# developed_drinking<-lm(data=Life,life_expectancy~least_developed + people_using_at_least_basic_drinking_water_services )
# summary(developed_drinking)
```

```{r}
# developed_health_grid<- emmeans(developed_health, specs = ~ least_developed,at =mean_health_expenditure)
# contrast(developed_health_grid, method = "pairwise")
# 
# developed_gdp_grid<- emmeans(developed_gdp, specs = ~ least_developed,at =mean_gdp)
# contrast(developed_gdp_grid, method = "pairwise")
# 
# developed_drinking_grid<- emmeans(developed_drinking, specs = ~ least_developed,at =mean_drinking)
# contrast(developed_drinking_grid, method = "pairwise")
```

